# Generated by Django 3.0.3 on 2020-04-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0003_auto_20200410_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='data_registrazione',
        ),
    ]
