# Generated by Django 3.0.3 on 2020-04-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0004_remove_utente_data_registrazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='data_registrazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
