# Generated by Django 3.0.3 on 2020-04-10 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0005_utente_data_registrazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='data_registrazione',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
